create or replace view public.outstanding_balances with (security_invoker = true) as
with sales_totals as (select shop_id,coalesce(sum(total_amount),0)::numeric as total_sold,count(*)::bigint as total_transactions,max(sold_at) as last_sale_at from public.sales where voided_at is null group by shop_id), return_totals as (select shop_id,coalesce(sum(total_loss),0)::numeric as total_returned from public.returns where voided_at is null group by shop_id), payment_totals as (select shop_id,coalesce(sum(amount),0)::numeric as total_paid,max(paid_at) as last_payment_at from public.payments where voided_at is null group by shop_id)
select s.id as shop_id,s.name as shop_name,s.owner_name,s.phone,s.address,s.credit_limit,coalesce(st.total_sold,0) as total_sold,coalesce(pt.total_paid,0) as total_paid,greatest(0::numeric,coalesce(st.total_sold,0)-coalesce(rt.total_returned,0)-coalesce(pt.total_paid,0)) as outstanding_amount,coalesce(st.total_transactions,0) as total_transactions,st.last_sale_at,pt.last_payment_at from public.shops s left join sales_totals st on st.shop_id=s.id left join return_totals rt on rt.shop_id=s.id left join payment_totals pt on pt.shop_id=s.id where s.is_active=true and (select private.is_admin());

create or replace view public.daily_analytics with (security_invoker = true) as
with days as (select distinct (sold_at at time zone 'Asia/Colombo')::date as day from public.sales where voided_at is null union select distinct (paid_at at time zone 'Asia/Colombo')::date from public.payments where voided_at is null union select distinct (spent_at at time zone 'Asia/Colombo')::date from public.expenses where voided_at is null union select distinct (returned_at at time zone 'Asia/Colombo')::date from public.returns where voided_at is null), ds as (select (sold_at at time zone 'Asia/Colombo')::date as day,sum(total_amount)::numeric as revenue,count(*)::bigint as transaction_count,count(distinct shop_id)::bigint as shops_served,sum(quantity)::bigint as units_sold from public.sales where voided_at is null group by 1), dp as (select (paid_at at time zone 'Asia/Colombo')::date as day,sum(amount)::numeric as collected from public.payments where voided_at is null group by 1), de as (select (spent_at at time zone 'Asia/Colombo')::date as day,sum(amount)::numeric as expenses from public.expenses where voided_at is null group by 1), dr as (select (returned_at at time zone 'Asia/Colombo')::date as day,sum(total_loss)::numeric as return_loss from public.returns where voided_at is null group by 1)
select d.day,coalesce(ds.revenue,0) as revenue,coalesce(dp.collected,0) as collected,coalesce(de.expenses,0) as expenses,coalesce(dr.return_loss,0) as return_loss,greatest(0::numeric,coalesce(ds.revenue,0)-coalesce(dr.return_loss,0)-coalesce(dp.collected,0)) as outstanding_created,coalesce(dp.collected,0)-coalesce(de.expenses,0) as net_deposit,coalesce(ds.transaction_count,0) as transaction_count,coalesce(ds.shops_served,0) as shops_served,coalesce(ds.units_sold,0) as units_sold from days d left join ds using(day) left join dp using(day) left join de using(day) left join dr using(day) where (select private.is_admin()) order by d.day desc;

create or replace view public.session_stock_reconciliation with (security_invoker = true) as
with loads as (select tl.session_id,tl.product_id,sum(tl.quantity_loaded)::numeric as loaded,sum(coalesce(tl.quantity_returned,0))::numeric as load_returned from public.truck_loads tl group by tl.session_id,tl.product_id), sold as (select sales.session_id,sales.product_id,sum(sales.quantity)::numeric as sold from public.sales where sales.session_id is not null and sales.voided_at is null group by sales.session_id,sales.product_id), returned as (select returns.session_id,returns.product_id,sum(returns.quantity)::numeric as returned from public.returns where returns.session_id is not null and returns.voided_at is null group by returns.session_id,returns.product_id)
select rs.id as session_id,rs.session_date,rs.driver_id,l.product_id,p.name as product_name,l.loaded,coalesce(s.sold,0) as sold,coalesce(r.returned,0) as returned,l.load_returned,(l.loaded-coalesce(s.sold,0)-coalesce(r.returned,0)) as expected_remaining,case when (l.loaded-coalesce(s.sold,0)-coalesce(r.returned,0))<0 then 'OVER_SOLD' when coalesce(r.returned,0)>l.loaded then 'OVER_RETURNED' else 'OK' end as status from loads l join public.route_sessions rs on rs.id=l.session_id join public.products p on p.id=l.product_id left join sold s on s.session_id=l.session_id and s.product_id=l.product_id left join returned r on r.session_id=l.session_id and r.product_id=l.product_id where (select private.is_admin());
