alter table public.sales add column if not exists voided_at timestamptz, add column if not exists voided_by uuid, add column if not exists void_reason text;
alter table public.payments add column if not exists voided_at timestamptz, add column if not exists voided_by uuid, add column if not exists void_reason text;
alter table public.returns add column if not exists voided_at timestamptz, add column if not exists voided_by uuid, add column if not exists void_reason text;
alter table public.expenses add column if not exists voided_at timestamptz, add column if not exists voided_by uuid, add column if not exists void_reason text;

create index if not exists idx_sales_active_shop on public.sales(shop_id) where voided_at is null;
create index if not exists idx_payments_active_shop on public.payments(shop_id) where voided_at is null;
create index if not exists idx_returns_active_shop on public.returns(shop_id) where voided_at is null;
create index if not exists idx_expenses_active_session on public.expenses(session_id) where voided_at is null;

revoke update, delete on public.sales, public.payments, public.returns, public.expenses from authenticated;

create or replace function private.admin_void_sale(p_sale_id uuid, p_reason text) returns uuid language plpgsql security definer set search_path='' as $$ declare v_record public.sales%rowtype; v_correction uuid; v_user uuid := (select auth.uid()); begin if not coalesce((select private.is_admin()),false) then raise exception 'Admin access required'; end if; if nullif(trim(p_reason),'') is null then raise exception 'Correction reason is required'; end if; select * into v_record from public.sales where id=p_sale_id for update; if not found then raise exception 'Sale not found'; end if; if v_record.voided_at is not null then raise exception 'Sale is already voided'; end if; update public.sales set voided_at=now(),voided_by=v_user,void_reason=trim(p_reason) where id=v_record.id; insert into public.corrections(table_name,record_id,action,old_values,new_values,corrected_by,reason) values('sales',v_record.id,'void',to_jsonb(v_record),to_jsonb((select s from public.sales s where s.id=v_record.id)),coalesce(v_user::text,'admin'),trim(p_reason)) returning id into v_correction; return v_correction; end; $$;
create or replace function private.admin_void_payment(p_payment_id uuid, p_reason text) returns uuid language plpgsql security definer set search_path='' as $$ declare v_record public.payments%rowtype; v_correction uuid; v_user uuid := (select auth.uid()); begin if not coalesce((select private.is_admin()),false) then raise exception 'Admin access required'; end if; if nullif(trim(p_reason),'') is null then raise exception 'Correction reason is required'; end if; select * into v_record from public.payments where id=p_payment_id for update; if not found then raise exception 'Payment not found'; end if; if v_record.voided_at is not null then raise exception 'Payment is already voided'; end if; update public.payments set voided_at=now(),voided_by=v_user,void_reason=trim(p_reason) where id=v_record.id; insert into public.corrections(table_name,record_id,action,old_values,new_values,corrected_by,reason) values('payments',v_record.id,'void',to_jsonb(v_record),to_jsonb((select p from public.payments p where p.id=v_record.id)),coalesce(v_user::text,'admin'),trim(p_reason)) returning id into v_correction; return v_correction; end; $$;
create or replace function private.admin_void_return(p_return_id uuid, p_reason text) returns uuid language plpgsql security definer set search_path='' as $$ declare v_record public.returns%rowtype; v_correction uuid; v_user uuid := (select auth.uid()); begin if not coalesce((select private.is_admin()),false) then raise exception 'Admin access required'; end if; if nullif(trim(p_reason),'') is null then raise exception 'Correction reason is required'; end if; select * into v_record from public.returns where id=p_return_id for update; if not found then raise exception 'Return not found'; end if; if v_record.voided_at is not null then raise exception 'Return is already voided'; end if; update public.returns set voided_at=now(),voided_by=v_user,void_reason=trim(p_reason) where id=v_record.id; insert into public.corrections(table_name,record_id,action,old_values,new_values,corrected_by,reason) values('returns',v_record.id,'void',to_jsonb(v_record),to_jsonb((select r from public.returns r where r.id=v_record.id)),coalesce(v_user::text,'admin'),trim(p_reason)) returning id into v_correction; return v_correction; end; $$;
revoke all on function private.admin_void_sale(uuid,text),private.admin_void_payment(uuid,text),private.admin_void_return(uuid,text) from public,anon,authenticated;
